/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef gemfire_CONSTANTS_H
#define gemfire_CONSTANTS_H

#include "gemfire_types.h"



class gemfireConstants {
 public:
  gemfireConstants();

};

extern const gemfireConstants g_gemfire_constants;



#endif
