/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "gemfire_constants.h"



const gemfireConstants g_gemfire_constants;

gemfireConstants::gemfireConstants() {
}



