// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "THGemfireService.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

//using namespace  ;

class THGemfireServiceHandler : virtual public THGemfireServiceIf {
 public:
  THGemfireServiceHandler() {
    // Your initialization goes here
  }

  void put(const std::string& regionName, const std::string& keyName, const std::map<std::string, std::string> & value) {
    // Your implementation goes here
    printf("put\n");
  }

  void get(std::map<std::string, std::string> & _return, const std::string& regionName, const std::string& keyName) {
    // Your implementation goes here
    printf("get\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<THGemfireServiceHandler> handler(new THGemfireServiceHandler());
  shared_ptr<TProcessor> processor(new THGemfireServiceProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

